/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.information_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ramya
 */
public class Frame extends javax.swing.JFrame {
    

    
    
    public Frame() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header_label = new javax.swing.JLabel();
        Name_label = new javax.swing.JLabel();
        Age_label = new javax.swing.JLabel();
        Phno_label = new javax.swing.JLabel();
        Name_text = new javax.swing.JTextField();
        Age_text = new javax.swing.JTextField();
        Phno_text = new javax.swing.JTextField();
        Insert_button = new javax.swing.JButton();
        Delete_button = new javax.swing.JButton();
        Update_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Student_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);

        Header_label.setBackground(java.awt.Color.white);
        Header_label.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        Header_label.setForeground(java.awt.Color.black);
        Header_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header_label.setText("STUDENT  INFORMATION   SYSTEM");

        Name_label.setBackground(java.awt.Color.white);
        Name_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        Name_label.setForeground(java.awt.Color.black);
        Name_label.setText("NAME");

        Age_label.setBackground(java.awt.Color.white);
        Age_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        Age_label.setForeground(java.awt.Color.black);
        Age_label.setText("AGE");

        Phno_label.setBackground(java.awt.Color.white);
        Phno_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        Phno_label.setForeground(java.awt.Color.black);
        Phno_label.setText("PHONE NO");

        Name_text.setBackground(java.awt.Color.white);
        Name_text.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        Name_text.setForeground(java.awt.Color.black);

        Age_text.setBackground(java.awt.Color.white);
        Age_text.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        Age_text.setForeground(java.awt.Color.black);

        Phno_text.setBackground(java.awt.Color.white);
        Phno_text.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        Phno_text.setForeground(java.awt.Color.black);

        Insert_button.setBackground(java.awt.Color.lightGray);
        Insert_button.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        Insert_button.setForeground(java.awt.Color.black);
        Insert_button.setText("INSERT");
        Insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_buttonActionPerformed(evt);
            }
        });

        Delete_button.setBackground(java.awt.Color.lightGray);
        Delete_button.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        Delete_button.setForeground(java.awt.Color.black);
        Delete_button.setText("DELETE");
        Delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_buttonActionPerformed(evt);
            }
        });

        Update_button.setBackground(java.awt.Color.lightGray);
        Update_button.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        Update_button.setForeground(java.awt.Color.black);
        Update_button.setText("UPDATE");
        Update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_buttonActionPerformed(evt);
            }
        });

        Student_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "AGE", "PHONE NO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Student_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Student_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Student_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Phno_label, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(Name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Age_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Name_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(Age_text, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Phno_text, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(Header_label, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Header_label, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Age_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Age_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Phno_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Phno_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(45, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     Connection con1;
     PreparedStatement insert;
     
//     TABLE UPDATE
     private void table_update(){
         int c;
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/DemoInfo","root","");
            insert = con1.prepareStatement("select * from Info");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            
            c = rss.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) Student_table.getModel();
            df.setRowCount(0);
            
            while(rs.next()){
                
                Vector v2 = new Vector();
                
                for(int a=1; a<=c;a++){
                    
                    v2.add(rs.getString("Id"));
                    v2.add(rs.getString("Name"));
                    v2.add(rs.getString("Age"));
                    v2.add(rs.getString("Phno"));
                    
                }
                df.addRow(v2);
                
            }
        
        } 
        catch (Exception ex){
            
        }
     }
     
    
//    INSERT OPERATION
    private void Insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_buttonActionPerformed
   
        String name = Name_text.getText();
        String age = Age_text.getText();
        String phno = Phno_text.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/DemoInfo","root","");
            insert = con1.prepareStatement("insert into Info(Name, Age, Phno)values(?,?,?)");
            insert.setString(1,name);
            insert.setString(2,age);
            insert.setString(3,phno);
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Inserted Successfully");
            table_update();
            
            Name_text.setText("");
            Age_text.setText("");
            Phno_text.setText("");
            Name_text.requestFocus();

        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Insert_buttonActionPerformed

//    DELETE OPERATION
    private void Delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_buttonActionPerformed

          DefaultTableModel model = (DefaultTableModel) Student_table.getModel();
          int selectedIndex = Student_table.getSelectedRow();
            try {   
                
            int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to Delete the record","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){

            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/DemoInfo","root","");
            insert = con1.prepareStatement("delete from Info where id = ?");
        
            insert.setInt(1,id);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Delete");
            Name_text.setText("");
            Age_text.setText("");
            Phno_text.setText("");

            table_update();
           
           }

        } catch (ClassNotFoundException ex) {
        
        } 
        catch (SQLException ex) {
            
        }
        
    }//GEN-LAST:event_Delete_buttonActionPerformed

//    UPDATE OPERATION
    private void Update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_buttonActionPerformed
        
        DefaultTableModel df = (DefaultTableModel) Student_table.getModel();       
        int selectedIndex = Student_table.getSelectedRow();
        
        try {
            int id = Integer.parseInt(df.getValueAt(selectedIndex, 0).toString());
            String name = Name_text.getText();
            String age = Age_text.getText();
            String phno = Phno_text.getText();
            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/DemoInfo","root","");
            insert = con1.prepareStatement("update Info set Name=?, Age=?, Phno=? where Id=?");
            insert.setString(1,name);
            insert.setString(2,age);
            insert.setString(3,phno);
            insert.setInt(4,id);
            insert.executeUpdate();
            
            
            JOptionPane.showMessageDialog(null,"Updated Successfully");
            table_update();
           
            Name_text.setText("");
            Age_text.setText("");
            Phno_text.setText("");
            Name_text.requestFocus();
         
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Update_buttonActionPerformed

//    Mouse Click Event On The Table
    private void Student_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_tableMouseClicked
       
        DefaultTableModel df = (DefaultTableModel) Student_table.getModel();
        
        int selectedIndex = Student_table.getSelectedRow();

        Name_text.setText(df.getValueAt(selectedIndex, 1).toString());
        Age_text.setText(df.getValueAt(selectedIndex, 2).toString());
        Phno_text.setText(df.getValueAt(selectedIndex, 3).toString());
        
    }//GEN-LAST:event_Student_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age_label;
    private javax.swing.JTextField Age_text;
    private javax.swing.JButton Delete_button;
    private javax.swing.JLabel Header_label;
    private javax.swing.JButton Insert_button;
    private javax.swing.JLabel Name_label;
    private javax.swing.JTextField Name_text;
    private javax.swing.JLabel Phno_label;
    private javax.swing.JTextField Phno_text;
    private javax.swing.JTable Student_table;
    private javax.swing.JButton Update_button;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
